// react-context-fetch-with_refresh/src/examples/home.tsx
import { useAuth } from '../hooks/use-auth'

const Home = () => {
  const auth = useAuth()

  const handleLogout = () => {
    void auth.logout()
  }

  return (
    <div>
      <h1>Home</h1>
      {auth.user ? (
        <>
          <p>Username: {auth.user.username}</p>
          <p>Email: {auth.user.email}</p>
          <button type="button" onClick={handleLogout}>
            Выйти
          </button>
        </>
      ) : null}
    </div>
  )
}

export default Home

// vue-pinia-axios-with_refresh/src/examples/home.vue
<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useAuthStore } from '../stores/auth-store'

const authStore = useAuthStore()
const { user } = storeToRefs(authStore)

const handleLogout = () => {
  void authStore.logout()
}
</script>

<template>
  <div>
    <h1>Home</h1>
    <template v-if="user">
      <p>Username: {{ user.username }}</p>
      <p>Email: {{ user.email }}</p>
      <button
        type="button"
        @click="handleLogout"
      >
        Выйти
      </button>
    </template>
  </div>
</template>
