// react-context-axios-with_refresh/src/examples/registration.tsx
import { FormEvent, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../hooks/use-auth'

const Registration = () => {
  const auth = useAuth()
  const navigate = useNavigate()
  const [username, setUsername] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState<string | null>(null)

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setError(null)

    auth.register(
      { username, email, password },
      () => {
        navigate('/login')
      },
      () => {
        setError('Не удалось зарегистрироваться')
      }
    )
  }

  return (
    <div>
      <h1>Registration</h1>
      <form onSubmit={handleSubmit}>
        <div>
          <label htmlFor="username">Username</label>
          <input
            id="username"
            type="text"
            value={username}
            onChange={(event) => setUsername(event.target.value)}
            required
          />
        </div>
        <div>
          <label htmlFor="email">Email</label>
          <input
            id="email"
            type="email"
            value={email}
            onChange={(event) => setEmail(event.target.value)}
            required
          />
        </div>
        <div>
          <label htmlFor="password">Password</label>
          <input
            id="password"
            type="password"
            value={password}
            onChange={(event) => setPassword(event.target.value)}
            required
          />
        </div>
        {error ? <p>{error}</p> : null}
        <button type="submit">Зарегистрироваться</button>
      </form>
      <p>
        <a href="/login">Уже есть аккаунт</a>
      </p>
    </div>
  )
}

export default Registration

// vue-pinia-axios-with_refresh/src/examples/registration.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth-store'

const authStore = useAuthStore()
const router = useRouter()

const username = ref('')
const email = ref('')
const password = ref('')
const error = ref<string | null>(null)

const handleSubmit = () => {
  error.value = null

  authStore.register(
    {
      username: username.value,
      email: email.value,
      password: password.value,
    },
    () => {
      router.push('/login')
    },
    () => {
      error.value = 'Не удалось зарегистрироваться'
    }
  )
}
</script>

<template>
  <div>
    <h1>Registration</h1>
    <form @submit.prevent="handleSubmit">
      <div>
        <label for="username">Username</label>
        <input
          id="username"
          v-model="username"
          type="text"
          required
        >
      </div>
      <div>
        <label for="email">Email</label>
        <input
          id="email"
          v-model="email"
          type="email"
          required
        >
      </div>
      <div>
        <label for="password">Password</label>
        <input
          id="password"
          v-model="password"
          type="password"
          required
        >
      </div>
      <p v-if="error">
        {{ error }}
      </p>
      <button type="submit">
        Зарегистрироваться
      </button>
    </form>
    <p>
      <RouterLink to="/login">
        Уже есть аккаунт
      </RouterLink>
    </p>
  </div>
</template>
