// react-context-axios-with_refresh/src/examples/login.tsx
import { FormEvent, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useAuth } from '../hooks/use-auth'

const Login = () => {
  const auth = useAuth()
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState<string | null>(null)

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setError(null)

    auth.login(
      { email, password },
      () => {
        const returnUrl = searchParams.get('returnUrl') || '/'
        navigate(returnUrl)
      },
      () => {
        setError('Неверный email или пароль')
      }
    )
  }

  return (
    <div>
      <h1>Login</h1>
      <form onSubmit={handleSubmit}>
        <div>
          <label htmlFor="email">Email</label>
          <input
            id="email"
            type="email"
            value={email}
            onChange={(event) => setEmail(event.target.value)}
            required
          />
        </div>
        <div>
          <label htmlFor="password">Password</label>
          <input
            id="password"
            type="password"
            value={password}
            onChange={(event) => setPassword(event.target.value)}
            required
          />
        </div>
        {error ? <p>{error}</p> : null}
        <button type="submit">Войти</button>
      </form>
      <p>
        <a href="/registration">Регистрация</a>
      </p>
    </div>
  )
}

export default Login

// vue-inject-fetch-with_refresh/src/examples/login.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuth } from '../composables/use-auth'

const auth = useAuth()
const router = useRouter()
const route = useRoute()

const email = ref('')
const password = ref('')
const error = ref<string | null>(null)

const handleSubmit = () => {
  error.value = null

  auth.login(
    { email: email.value, password: password.value },
    () => {
      const returnUrl =
        typeof route.query.returnUrl === 'string'
          ? route.query.returnUrl
          : '/'
      router.push(returnUrl)
    },
    () => {
      error.value = 'Неверный email или пароль'
    }
  )
}
</script>

<template>
  <div>
    <h1>Login</h1>
    <form @submit.prevent="handleSubmit">
      <div>
        <label for="email">Email</label>
        <input
          id="email"
          v-model="email"
          type="email"
          required
        >
      </div>
      <div>
        <label for="password">Password</label>
        <input
          id="password"
          v-model="password"
          type="password"
          required
        >
      </div>
      <p v-if="error">
        {{ error }}
      </p>
      <button type="submit">
        Войти
      </button>
    </form>
    <p>
      <RouterLink to="/registration">
        Регистрация
      </RouterLink>
    </p>
  </div>
</template>
